### PR TITLE
very rough attempt to add .net6.0

### PR DESCRIPTION
**Pull request by paul42**
Need to work on how to get tests to run properly and verify that it all works, but are there any objections if I remove the third party library and work with the system.text.json library included with the framework? I think we can simplify the code from 3.1=>6.0 by using more built in features to make reading and understanding the code a bit quicker and easier.

please let me know your thoughts, Thanks!

### CODE REVIEW

**Comment by rabbah** [comment]
Thanks for the contribution @paul42!

**Comment by paul42** [comment]
@rabbah or @dgrove-oss how long should Travis CI spin? it looks like it's still in 'job received' and not yet queued. is that normal?

**Comment by rabbah** [comment]
I've seen it on occasion - I just gave it a kick.

**Comment by paul42** [comment]
hmmm I need to figure out why the container isn't responding. maybe I'm not building the test package correctly or something

**Comment by shawnallen85** [comment]
Sorry for the delay. @paul42 were you able to get the tests running locally? The most recent Travis CI build for this had failed.

**Comment by shawnallen85** [comment]
I was able to clone your repo and run the tests locally -- there are a number of errors that need to be resolved.

I like going forward with using System.Text.Json rather than Json.NET to remove the additional dependency and it'll *finally* resolve https://github.com/apache/openwhisk-runtime-dotnet/issues/51. I've been holding off on making that change for a new LTS runtime to be released.

I think it would be worth adding some additional wording to state that migration and link to (or provide details on) porting existing functions over.

To get the test running locally, could you give this a try?

In a **new** directory ...
```bash
git clone git@github.com:apache/openwhisk.git
cd openwhisk
export OPENWHISK_HOME=`pwd`
cd ..
git clone git@github.com:paul42/openwhisk-runtime-dotnet.git
cd openwhisk-runtime-dotnet

pushd $OPENWHISK_HOME
./gradlew install
podd $OPENWHISK_HOME

./gradlew :tests:test --tests DotNet6_0ActionContainerTests
```

It might make sense to pull back on some of the refactoring and use the `3.1` codebase as a guide and update things as described by [Microsoft on upgrading projects](https://docs.microsoft.com/en-us/aspnet/core/migration/31-to-60?view=aspnetcore-6.0&tabs=visual-studio).

LKM if this is asking a lot, I've been meaning to dive into this code and get things updated for the new runtime.

Thanks!!

**Comment by paul42** [comment]
Hey @shawnallen85 Thanks for taking a look, I appreciate any help you can give 👍 give me a bit to try it. I'm also not certain how to set up the scala tests so I was making a guess in the dark, so if I didn't copy or format it correctly that might also be a factor.

**Comment by shawnallen85** [comment]
@paul42 Any luck with remigrating the 3.1 runtime to 6.0, but in smaller chunks (for testing and seeing where issues are coming up from the tests)? And, any luck with getting the tests running?

**Comment by dgrove-oss** [comment]
redundant with #68

**Pull request closed without merging**
