### PR TITLE
Add travis hooks to test and publish docker images.

### PR DESCRIPTION
**Pull request by rabbah**
@csantanapr @dgrove-oss might need your help re-encrypting slack notification and dockerhub info.

### CODE REVIEW

**Comment by csantanapr** [comment]
>@csantanapr @dgrove-oss might need your help re-encrypting slack notification and dockerhub info.

@rabbah for the dockehub credentials to push "nightlys"  the creds are in Apache ppmc svn private directory

Unless you want me to do it, I have it setup locally in my laptop.

**Comment by csantanapr** [comment]
For the Slack, I have no idea what's the URL @dgrove-oss did that last time, I don't know if he saved it in the ppmc directory

**Comment by rabbah** [comment]
Since you have it setup locally do you mind pushing to my branch? 🙏🏼

**Comment by dgrove-oss** [comment]
travis2slack done.   I am loving the newish 'edit the file in the github ui' functionality.

**Comment by csantanapr** [comment]
@rabbah pushed travis secret for dh

**Review by csantanapr — APPROVED** [review]

**Pull request merged**
