### PR TITLE
.NET 6.0 Support

### PR DESCRIPTION
**Pull request by shawnallen85**
Removed .NET Core 2.2 since it is no longer supported by Microsoft.

Added .NET 6.0.

Added Vagrant for development purposes.

### CODE REVIEW

**Comment by ElanHasson** [comment]
Hi @shawnallen85, This is awesome, thanks for putting this together! 

Did you opt for .NET 6 over 7 because it is the LTS release?

**Comment by shawnallen85** [comment]
Elan,

That is correct.

Thanks,

Shawn

**Comment by mattwelke** [comment]
@shawnallen85 I notice that in https://github.com/apache/openwhisk-runtime-dotnet/pull/61, the PR creator switches it from Newtonsoft to System.Json.Text and you commented saying that you agreed with that change. Any plans to do the same for this PR?

**Comment by shawnallen85** [comment]
@mattwelke #61 isn't from me. I don't think changing the default JSON serializer makes sense yet as System.Text.Json doesn't have feature parity when compared to Newtonsoft.Json.

Going back a few months, there was a discussion about abstracting the serialization to where the function owner could pick the serializer, but I haven't seem much feedback from that idea (other than I think your feedback if I recall).

**Review by dgrove-oss — APPROVED** [review]
LGTM - please go ahead and merge.

**Review by ElanHasson — APPROVED** [review]

**Pull request merged**
